name: chia_simulator_dart_implementation
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  chia_utils:
    git: https://github.com/irulast/chia-crypto-utils.git
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
